### ISSUE TITLE
Questions about cluster threshold

### ISSUE THREAD

**Issue by agoodStu** [SkeideLab/meta_semantics#1]
In `nb01_ale.py`, `run_ale()` function,

> cluster_thresh_z = norm.ppf(1 - cluster_thresh / 2)
> img_clust_thresh = image.threshold_img(img=img_clust, threshold=cluster_thresh_z)

Could you tell me why you set `threshold=cluster_thresh_z`, please. I don't figure it out after Google. 
Can I set `threshold = "100%" `?  What difference would that make?

Thank you.

**Comment by alexenge** [comment]
This is done so we can define our `cluster_thresh` (cluster-level, FWE-corrected statistical threshold) as a *p* value, as is common in psychology and cognitive neuroscience. We had to convert this *p* value into a *z* score so that we could easily threshold the cluster-level statistical map that was created by the `FWECorrector` (which contains the FWE-corrected *z* scores for the clusters).

Please see [Eickhoff et al. (2016, *NeuroImage*)](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC4981641/) for a simulation-based discussion of this and other types of cluster-level thresholds for ALE meta-analyses.

If you would use a percentage (e.g., `"90%"`) instead of a *z* score as your `threshold`, your thresholded map wouldn't correspond to any "meaningful" statistical threshold (e.g., *p* < .01). Instead, it would only show you the largest 10% of clusters in the map.

**Comment by agoodStu** [comment]
> This is done so we can define our `cluster_thresh` (cluster-level, FWE-corrected statistical threshold) as a _p_ value, as is common in psychology and cognitive neuroscience. We had to convert this _p_ value into a _z_ score so that we could easily threshold the cluster-level statistical map that was created by the `FWECorrector` (which contains the FWE-corrected _z_ scores for the clusters).
> 
> Please see [Eickhoff et al. (2016, _NeuroImage_)](https://www.ncbi.nlm.nih.gov/labs/pmc/articles/PMC4981641/) for a simulation-based discussion of this and other types of cluster-level thresholds for ALE meta-analyses.
> 
> If you would use a percentage (e.g., `"90%"`) instead of a _z_ score as your `threshold`, your thresholded map wouldn't correspond to any "meaningful" statistical threshold (e.g., _p_ < .01). Instead, it would only show you the largest 10% of clusters in the map.

Hi,  alexenge.
I appreciate your reply.  I changed the `cluster_thresh_z ` back to what it was in your code. After running the following code, I got a  `UserWarning`
```
# %%
# Perform the ALE analysis for adults
_ = run_ale(
    text_file=output_dir + "safe.txt",
    voxel_thresh=0.001,
    cluster_thresh=0.05,
    random_seed=1234,
    n_iters=1000,
    output_dir=output_dir,
)

---
C:\Users\HUAS\anaconda3\lib\site-packages\nilearn\_utils\param_validation.py:72: 
UserWarning: The given float value must not exceed 1.8807936081512509. But, you have given threshold=1.959963984540054
warnings.warn("The given float value must not exceed {0}. " 
```
Next, I ran the following code, , which shows that mask is empty
```
formula = "np.where(img1 * img2 > 0, np.minimum(img1, img2), 0)"
img_safe_z = image.load_img(output_dir + "safe_z_thresh.nii.gz")
p = plotting.plot_glass_brain(img_safe_z, display_mode="lyrz", colorbar=True)

---
C:\Users\HUAS\anaconda3\lib\site-packages\nilearn\plotting\displays.py:880: UserWarning: empty mask
  get_mask_bounds(new_img_like(img, not_mask, affine))
```
I don't know if this means there is a problem with my meta-analysis, especially in literature selection.  There are 17 experiments in my meta-analysis. Should I add more experiments? 

I'm sorry for asking so many stupid questions. 
Thanks again for your reply.

**Comment by alexenge** [comment]
These questions are definitely not stupid!

This result means that there are no significant clusters in your meta-analysis given the pre-specified threshold that we have used. This could be either because there is really no overlap in your experiments (e.g., because the tasks are two different) or because you don't have enough statistical power. The latter is quite probable given that 17 experiments is a rather small sample size for an ALE meta-analyses (again, see the Eickhoff et al. paper).

You could plot the non-thresholded *z* score maps (the ones in the `results/ale` that end in `_z.nii.gz` instead of `_z_thresh.nii.gz`) to see if there are any clusters that look plausible but are just below the threshold (due to a lack of power).

**Comment by agoodStu** [comment]
Hi, alexenge.
I'm very grateful to your suggestions. I'll check non-thresholded z score maps and read paper again. 
Can I leave this `Issues` open in case I ask you another question, please? I hope it doesn't look impolite.  I'll figure this out as soon as POSSIBLE. 
May you have a nice weekend!

**Comment by alexenge** [comment]
No worries!

**Comment by agoodStu** [comment]
Hi, alexenge. 
I've solved that problem. I appreciate all your help. It helps me save a lot of time and makes me have enough time to study.
I'll close the issues.
Best wishes.
